CREATE TABLE todo (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	title TEXT,
  desc TEXT,
	task INT(2) NOT NULL DEFAULT 0,
	create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);